esphome:
  name: $devicename
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pw
  #domain: .jonn26.lan

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_rest_pw

ota:
  password: !secret esphome_ota_pw

sensor:
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "$upper_devicename Uptime"

binary_sensor:
#Atom button
  - platform: gpio
    pin: GPIO39
    name: $upper_devicename Button

  - platform: status
    name: $upper_devicename Status
    id: status_sensor


  - platform: esp32_touch
    name: "$upper_devicename Touch"
    pin: GPIO33
    threshold: 1000
# if touch sensor active then turn led red
    on_press:
      then:
      - light.turn_on:
          id: status_led
          brightness: 20%
          red: 100%
          green: 0%
          blue: 0%
          transition_length: 100ms
# otherwise led is greed
    on_release:
      - light.turn_on:
          id: status_led
          brightness: 20%
          red: 0%
          green: 100%
          blue: 0%
          transition_length: 100ms


light:
  #atom neopixel led on the button
  - platform: neopixelbus
    type: GRB
    variant: SK6812
    pin: GPIO27
    num_leds: 1
    id: status_led
    restore_mode: ALWAYS_OFF

esp32_touch:
  #setup_mode: True
  iir_filter: 10ms
